import matter from "gray-matter";
import Link from "next/link";
import fs from "fs";
import path from "path";
import { projectsFilePaths, PROJECTS_PATH } from "../../utils/mdxUtils";

export default function BlogIndex({ posts }) {
  console.log("BlogIndex");
  return (
    <div>
      <h1>Home Page</h1>
      <p>
        Click the link below to navigate to a page generated by{" "}
        <code>next-mdx-remote</code>.
      </p>
      <ul>
        {posts.map((post) => (
          <li key={post.filePath}>
            <Link
              as={`/blog/${post.filePath.replace(/\.mdx?$/, "")}`}
              href={`/blog/[slug]`}
            >
              <a>{post.data.title}</a>
            </Link>
          </li>
        ))}
      </ul>
    </div>
  );
}
console.log("IMPORTED");
export function getStaticProps() {
  console.log("getStaticProps", projectsFilePaths);
  const posts = projectsFilePaths.map((filePath) => {
    const source = fs.readFileSync(path.join(PROJECTS_PATH, filePath));
    const { content, data } = matter(source);

    return {
      content,
      data,
      filePath,
    };
  });

  return { props: { posts } };
}
